---

- name: Install Pacman packages
  become: true
  become_method: su
  become_user: root
  remote_user: rpi
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - python-pip
    - sudo
    - wpa_supplicant
    - vim
    - dialog
    - git
    - gcc
    - openssl
    - pkg-config
    - libffi
    - netctl
    - xorg-xinit
    - xorg-server
    - xf86-video-fbdev
    - chromium

