
 - hosts: all
   become: yes
   become_user: root
   become_method: su
   gather_facts: no
   pre_tasks:
       - name: 'Install python'
         raw: pacman --noconfirm --needed -S python sudo
   vars_files:
      - variables
   roles:
       - role: install_user

