
 - hosts: all
   become: yes
   become_user: root
   become_method: su
   gather_facts: no
   pre_tasks:
       - name: 'Install python'
         raw: pacman --noconfirm --needed -S python
   vars_files:
      - variables
   roles:
       - role: install_boot
       - role: install_network
       - role: install_user
       - role: install_basic_packages
       - role: create_directory_structure
       - role: clone_repos
       - role: install_piserver
       - role: install_chromium_service

