
 - hosts: all
   roles:
       - role: install_basic_packages
       - role: install_user
       - role: create_directory_structure
       - role: install_updater
       - role: clone_repos
       - role: install_piserver
       - role: install_chromium_service

