---

- name: Create Wifi Config file
  become: yes
  become_user: root
  become_method: su
  template: src=wlan0-profile dest=/etc/netctl/wlan0-profile mode="u=r"
  vars:
    SSID: "{{WIFI_NAME}}"
    PWD: "{{WIFI_PASSWD}}"

- name: Enable Wifi
  become: yes
  become_user: root
  become_method: su
  shell: netctl enable wlan0-profile

