- name: "Cloning: {{repo.name}}"
  git:
   repo: "{{ repo.url }}"
   dest: "/home/rpi/Code/{{ repo.name }}"
   clone: yes
   update: no
   accept_hostkey: yes
   force: yes

- name: "Set git config user.name"
- git_config:
    name: user.name
    repo: "/home/rpi/Code/{{ repo.name }}"
    scope: local
    value: 'Temp name'

- name: "Set git config user.email"
- git_config:
    name: user.email
    repo: "/home/rpi/Code/{{ repo.name }}"
    scope: local
    value: 'temp@email.com'

