---

- name: Setup repositories
  ignore_errors: yes
  include: gitclone.yml repo={{item}}
  with_items:
    - { url: 'https://github.com/supersaiyanmode/HomePiDeployment.git', name: 'HomePiDeployment'}
    - { url: 'https://github.com/supersaiyanmode/HomePiServer.git', name: 'HomePiServer'}

