---

- name: Clone the Main Deployment repository
  git:
     repo: 'git@github.com:supersaiyanmode/HomePiDeployment.git'
     dest: /home/rpi/Code/HomePiDeployment
     key_file: /home/rpi/.ssh/id_rsa-HomePiDeployment
     clone: yes
     update: no
     accept_hostkey: yes
     force: yes
  ignore_errors: yes

