---
- name: Create logger directory.
  sudo: yes
  file:
    path: /var/log/piserver
    state: directory
    mode: 0755
    owner: rpi
    group: rpi

- name: Install HomePiServer unit.
  sudo: yes
  copy:
    src: piserver.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"


- name: Get libffi cflags
  shell: "pkg-config --cflags libffi"
  register: cflags


- name: Get libffi libs
  shell: "pkg-config --libs libffi"
  register: libs


- name: Install server dependencies.
  sudo: yes
  environment:
    CFLAGS: "{{ cflags.stdout }}"
    LDFLAGS: "{{ libs.stdout }}"
  pip:
    requirements: /home/rpi/Code/HomePiServer/requirements.txt
    executable: pip

- name: Enable HomePiServer unit
  sudo: yes
  systemd:
    state: started
    enabled: yes
    name: piserver.service
    daemon_reload: yes

