---
- name: Create logger directory.
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  file:
    path: /var/log/piserver
    state: directory
    mode: 0755
    owner: rpi
    group: rpi

- name: Install HomePiServer unit.
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  copy:
    src: piserver.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"


- name: Get libffi cflags
  shell: "pkg-config --cflags libffi"
  register: cflags


- name: Get libffi libs
  shell: "pkg-config --libs libffi"
  register: libs


- name: Install server dependencies.
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  environment:
    CFLAGS: "{{ cflags.stdout }}"
    LDFLAGS: "{{ libs.stdout }}"
  pip:
    requirements: /home/rpi/Code/HomePiServer/requirements.txt
    executable: pip

- name: Enable HomePiServer unit
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  systemd:
    state: started
    enabled: yes
    name: piserver.service
    daemon_reload: yes

- name: Copy scripts to check updates.
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  copy:
     src: check_updates.sh
     dest: /home/rpi/scripts
     owner: rpi
     group: rpi
     mode: "u=rx"


- name: Copy scripts to run updates.
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  copy:
     src: update_repos.sh
     dest: /home/rpi/scripts
     owner: rpi
     group: rpi
     mode: "u=rx"


- name: Copy scripts to run ansible.
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  copy:
     src: run_ansible.sh
     dest: /home/rpi/scripts
     owner: rpi
     group: rpi
     mode: "u=rx"


- name: Copy scripts to reboot.
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  copy:
     src: reboot.sh
     dest: /home/rpi/scripts
     owner: rpi
     group: rpi
     mode: "u=rx"



- name: Copy scripts to shutdown.
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  copy:
     src: shutdown.sh
     dest: /home/rpi/scripts
     owner: rpi
     group: rpi
     mode: "u=rx"


