---

- name: Install Chromium Service File
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  copy:
    src: display.service
    dest: /etc/systemd/system/display.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"


- name: Install .xinitrc
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  copy:
    src: xinitrc
    dest: /home/rpi/.xinitrc
    owner: rpi
    group: rpi
    mode: "u=rw"


- name: Enable Chromium Service unit
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  systemd:
    state: started
    enabled: yes
    name: display.service
    daemon_reload: yes

- name: Install Xwrapper
  remote_user: rpi
  become: true
  become_method: su
  become_user: root
  copy:
    src: Xwrapper.config
    dest: /etc/X11/Xwrapper.config
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"


