---

- name: Clone the repository
  git:
     repo: 'git@github.com:supersaiyanmode/HomePiDeployment.git'
     dest: /home/rpi/Code/HomePiDeployment
     update: yes
     accept_hostkey: yes
     force: yes
  ignore_errors: yes
