---
- name: Create rpi user
  sudo: yes
  user:
    name: rpi
    shell: /bin/bash
	state: present
	createhome: yes
    groups: video,lp,audio,wheel

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

