---

- name: Copy over the Redis config file.
  remote_user: rpi
  become: true
  become_method: sudo
  become_user: root
  copy:
    src: redis.conf
    dest: /etc/redis.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Install Redis service.
  remote_user: rpi
  become: true
  become_method: sudo
  become_user: root
  systemd:
    state: started
    enabled: yes
    name: redis.service
    daemon_reload: yes


- name: Set Redis password
  remote_user: rpi
  become: true
  become_method: sudo
  become_user: root
  lineinfile:
    path: /etc/redis.conf
    regexp: '^requirepass'
    line: "requirepass={{REDIS_PASSWD}}"

